package com.learn.yzh.common.model;

import java.io.Serializable;
import java.util.Date;

public class Member implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_code
     *
     * @mbggenerated
     */
    private String memberCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_owner
     *
     * @mbggenerated
     */
    private String memberOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_password
     *
     * @mbggenerated
     */
    private String memberPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_phone
     *
     * @mbggenerated
     */
    private String memberPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_name
     *
     * @mbggenerated
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_sex
     *
     * @mbggenerated
     */
    private String memberSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_birthday
     *
     * @mbggenerated
     */
    private Date memberBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_address
     *
     * @mbggenerated
     */
    private String memberAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_head_img
     *
     * @mbggenerated
     */
    private String memberHeadImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_id_type
     *
     * @mbggenerated
     */
    private String memberIdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_id_num
     *
     * @mbggenerated
     */
    private String memberIdNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_education
     *
     * @mbggenerated
     */
    private String memberEducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_income
     *
     * @mbggenerated
     */
    private String memberIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_balance
     *
     * @mbggenerated
     */
    private Integer memberBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_credit_used
     *
     * @mbggenerated
     */
    private Integer memberCreditUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_credit
     *
     * @mbggenerated
     */
    private Integer memberCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_level
     *
     * @mbggenerated
     */
    private Integer memberLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.credit_updatetime
     *
     * @mbggenerated
     */
    private Date creditUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.level_updatetime
     *
     * @mbggenerated
     */
    private Date levelUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.regist_datetime
     *
     * @mbggenerated
     */
    private Date registDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.last_consume_datetime
     *
     * @mbggenerated
     */
    private Date lastConsumeDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.member_mood
     *
     * @mbggenerated
     */
    private String memberMood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.balance_pwd
     *
     * @mbggenerated
     */
    private String balancePwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.wechat_account
     *
     * @mbggenerated
     */
    private String wechatAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.wechat_name
     *
     * @mbggenerated
     */
    private String wechatName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.wechat_image
     *
     * @mbggenerated
     */
    private String wechatImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.wechat_unionid
     *
     * @mbggenerated
     */
    private String wechatUnionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.invite_code
     *
     * @mbggenerated
     */
    private String inviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.smallroutine_unionid
     *
     * @mbggenerated
     */
    private String smallroutineUnionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.phone_type
     *
     * @mbggenerated
     */
    private Integer phoneType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loyalty_member.push_id
     *
     * @mbggenerated
     */
    private String pushId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_loyalty_member
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_code
     *
     * @return the value of t_loyalty_member.member_code
     *
     * @mbggenerated
     */
    public String getMemberCode() {
        return memberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_code
     *
     * @param memberCode the value for t_loyalty_member.member_code
     *
     * @mbggenerated
     */
    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode == null ? null : memberCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_owner
     *
     * @return the value of t_loyalty_member.member_owner
     *
     * @mbggenerated
     */
    public String getMemberOwner() {
        return memberOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_owner
     *
     * @param memberOwner the value for t_loyalty_member.member_owner
     *
     * @mbggenerated
     */
    public void setMemberOwner(String memberOwner) {
        this.memberOwner = memberOwner == null ? null : memberOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_password
     *
     * @return the value of t_loyalty_member.member_password
     *
     * @mbggenerated
     */
    public String getMemberPassword() {
        return memberPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_password
     *
     * @param memberPassword the value for t_loyalty_member.member_password
     *
     * @mbggenerated
     */
    public void setMemberPassword(String memberPassword) {
        this.memberPassword = memberPassword == null ? null : memberPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_phone
     *
     * @return the value of t_loyalty_member.member_phone
     *
     * @mbggenerated
     */
    public String getMemberPhone() {
        return memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_phone
     *
     * @param memberPhone the value for t_loyalty_member.member_phone
     *
     * @mbggenerated
     */
    public void setMemberPhone(String memberPhone) {
        this.memberPhone = memberPhone == null ? null : memberPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_name
     *
     * @return the value of t_loyalty_member.member_name
     *
     * @mbggenerated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_name
     *
     * @param memberName the value for t_loyalty_member.member_name
     *
     * @mbggenerated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_sex
     *
     * @return the value of t_loyalty_member.member_sex
     *
     * @mbggenerated
     */
    public String getMemberSex() {
        return memberSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_sex
     *
     * @param memberSex the value for t_loyalty_member.member_sex
     *
     * @mbggenerated
     */
    public void setMemberSex(String memberSex) {
        this.memberSex = memberSex == null ? null : memberSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_birthday
     *
     * @return the value of t_loyalty_member.member_birthday
     *
     * @mbggenerated
     */
    public Date getMemberBirthday() {
        return memberBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_birthday
     *
     * @param memberBirthday the value for t_loyalty_member.member_birthday
     *
     * @mbggenerated
     */
    public void setMemberBirthday(Date memberBirthday) {
        this.memberBirthday = memberBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_address
     *
     * @return the value of t_loyalty_member.member_address
     *
     * @mbggenerated
     */
    public String getMemberAddress() {
        return memberAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_address
     *
     * @param memberAddress the value for t_loyalty_member.member_address
     *
     * @mbggenerated
     */
    public void setMemberAddress(String memberAddress) {
        this.memberAddress = memberAddress == null ? null : memberAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_head_img
     *
     * @return the value of t_loyalty_member.member_head_img
     *
     * @mbggenerated
     */
    public String getMemberHeadImg() {
        return memberHeadImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_head_img
     *
     * @param memberHeadImg the value for t_loyalty_member.member_head_img
     *
     * @mbggenerated
     */
    public void setMemberHeadImg(String memberHeadImg) {
        this.memberHeadImg = memberHeadImg == null ? null : memberHeadImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_id_type
     *
     * @return the value of t_loyalty_member.member_id_type
     *
     * @mbggenerated
     */
    public String getMemberIdType() {
        return memberIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_id_type
     *
     * @param memberIdType the value for t_loyalty_member.member_id_type
     *
     * @mbggenerated
     */
    public void setMemberIdType(String memberIdType) {
        this.memberIdType = memberIdType == null ? null : memberIdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_id_num
     *
     * @return the value of t_loyalty_member.member_id_num
     *
     * @mbggenerated
     */
    public String getMemberIdNum() {
        return memberIdNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_id_num
     *
     * @param memberIdNum the value for t_loyalty_member.member_id_num
     *
     * @mbggenerated
     */
    public void setMemberIdNum(String memberIdNum) {
        this.memberIdNum = memberIdNum == null ? null : memberIdNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_education
     *
     * @return the value of t_loyalty_member.member_education
     *
     * @mbggenerated
     */
    public String getMemberEducation() {
        return memberEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_education
     *
     * @param memberEducation the value for t_loyalty_member.member_education
     *
     * @mbggenerated
     */
    public void setMemberEducation(String memberEducation) {
        this.memberEducation = memberEducation == null ? null : memberEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_income
     *
     * @return the value of t_loyalty_member.member_income
     *
     * @mbggenerated
     */
    public String getMemberIncome() {
        return memberIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_income
     *
     * @param memberIncome the value for t_loyalty_member.member_income
     *
     * @mbggenerated
     */
    public void setMemberIncome(String memberIncome) {
        this.memberIncome = memberIncome == null ? null : memberIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_balance
     *
     * @return the value of t_loyalty_member.member_balance
     *
     * @mbggenerated
     */
    public Integer getMemberBalance() {
        return memberBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_balance
     *
     * @param memberBalance the value for t_loyalty_member.member_balance
     *
     * @mbggenerated
     */
    public void setMemberBalance(Integer memberBalance) {
        this.memberBalance = memberBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_credit_used
     *
     * @return the value of t_loyalty_member.member_credit_used
     *
     * @mbggenerated
     */
    public Integer getMemberCreditUsed() {
        return memberCreditUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_credit_used
     *
     * @param memberCreditUsed the value for t_loyalty_member.member_credit_used
     *
     * @mbggenerated
     */
    public void setMemberCreditUsed(Integer memberCreditUsed) {
        this.memberCreditUsed = memberCreditUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_credit
     *
     * @return the value of t_loyalty_member.member_credit
     *
     * @mbggenerated
     */
    public Integer getMemberCredit() {
        return memberCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_credit
     *
     * @param memberCredit the value for t_loyalty_member.member_credit
     *
     * @mbggenerated
     */
    public void setMemberCredit(Integer memberCredit) {
        this.memberCredit = memberCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_level
     *
     * @return the value of t_loyalty_member.member_level
     *
     * @mbggenerated
     */
    public Integer getMemberLevel() {
        return memberLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_level
     *
     * @param memberLevel the value for t_loyalty_member.member_level
     *
     * @mbggenerated
     */
    public void setMemberLevel(Integer memberLevel) {
        this.memberLevel = memberLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.credit_updatetime
     *
     * @return the value of t_loyalty_member.credit_updatetime
     *
     * @mbggenerated
     */
    public Date getCreditUpdatetime() {
        return creditUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.credit_updatetime
     *
     * @param creditUpdatetime the value for t_loyalty_member.credit_updatetime
     *
     * @mbggenerated
     */
    public void setCreditUpdatetime(Date creditUpdatetime) {
        this.creditUpdatetime = creditUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.level_updatetime
     *
     * @return the value of t_loyalty_member.level_updatetime
     *
     * @mbggenerated
     */
    public Date getLevelUpdatetime() {
        return levelUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.level_updatetime
     *
     * @param levelUpdatetime the value for t_loyalty_member.level_updatetime
     *
     * @mbggenerated
     */
    public void setLevelUpdatetime(Date levelUpdatetime) {
        this.levelUpdatetime = levelUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.regist_datetime
     *
     * @return the value of t_loyalty_member.regist_datetime
     *
     * @mbggenerated
     */
    public Date getRegistDatetime() {
        return registDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.regist_datetime
     *
     * @param registDatetime the value for t_loyalty_member.regist_datetime
     *
     * @mbggenerated
     */
    public void setRegistDatetime(Date registDatetime) {
        this.registDatetime = registDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.last_consume_datetime
     *
     * @return the value of t_loyalty_member.last_consume_datetime
     *
     * @mbggenerated
     */
    public Date getLastConsumeDatetime() {
        return lastConsumeDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.last_consume_datetime
     *
     * @param lastConsumeDatetime the value for t_loyalty_member.last_consume_datetime
     *
     * @mbggenerated
     */
    public void setLastConsumeDatetime(Date lastConsumeDatetime) {
        this.lastConsumeDatetime = lastConsumeDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.member_mood
     *
     * @return the value of t_loyalty_member.member_mood
     *
     * @mbggenerated
     */
    public String getMemberMood() {
        return memberMood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.member_mood
     *
     * @param memberMood the value for t_loyalty_member.member_mood
     *
     * @mbggenerated
     */
    public void setMemberMood(String memberMood) {
        this.memberMood = memberMood == null ? null : memberMood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.login_time
     *
     * @return the value of t_loyalty_member.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.login_time
     *
     * @param loginTime the value for t_loyalty_member.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.balance_pwd
     *
     * @return the value of t_loyalty_member.balance_pwd
     *
     * @mbggenerated
     */
    public String getBalancePwd() {
        return balancePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.balance_pwd
     *
     * @param balancePwd the value for t_loyalty_member.balance_pwd
     *
     * @mbggenerated
     */
    public void setBalancePwd(String balancePwd) {
        this.balancePwd = balancePwd == null ? null : balancePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.source
     *
     * @return the value of t_loyalty_member.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.source
     *
     * @param source the value for t_loyalty_member.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.wechat_account
     *
     * @return the value of t_loyalty_member.wechat_account
     *
     * @mbggenerated
     */
    public String getWechatAccount() {
        return wechatAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.wechat_account
     *
     * @param wechatAccount the value for t_loyalty_member.wechat_account
     *
     * @mbggenerated
     */
    public void setWechatAccount(String wechatAccount) {
        this.wechatAccount = wechatAccount == null ? null : wechatAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.wechat_name
     *
     * @return the value of t_loyalty_member.wechat_name
     *
     * @mbggenerated
     */
    public String getWechatName() {
        return wechatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.wechat_name
     *
     * @param wechatName the value for t_loyalty_member.wechat_name
     *
     * @mbggenerated
     */
    public void setWechatName(String wechatName) {
        this.wechatName = wechatName == null ? null : wechatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.wechat_image
     *
     * @return the value of t_loyalty_member.wechat_image
     *
     * @mbggenerated
     */
    public String getWechatImage() {
        return wechatImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.wechat_image
     *
     * @param wechatImage the value for t_loyalty_member.wechat_image
     *
     * @mbggenerated
     */
    public void setWechatImage(String wechatImage) {
        this.wechatImage = wechatImage == null ? null : wechatImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.wechat_unionid
     *
     * @return the value of t_loyalty_member.wechat_unionid
     *
     * @mbggenerated
     */
    public String getWechatUnionid() {
        return wechatUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.wechat_unionid
     *
     * @param wechatUnionid the value for t_loyalty_member.wechat_unionid
     *
     * @mbggenerated
     */
    public void setWechatUnionid(String wechatUnionid) {
        this.wechatUnionid = wechatUnionid == null ? null : wechatUnionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.invite_code
     *
     * @return the value of t_loyalty_member.invite_code
     *
     * @mbggenerated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.invite_code
     *
     * @param inviteCode the value for t_loyalty_member.invite_code
     *
     * @mbggenerated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.smallroutine_unionid
     *
     * @return the value of t_loyalty_member.smallroutine_unionid
     *
     * @mbggenerated
     */
    public String getSmallroutineUnionid() {
        return smallroutineUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.smallroutine_unionid
     *
     * @param smallroutineUnionid the value for t_loyalty_member.smallroutine_unionid
     *
     * @mbggenerated
     */
    public void setSmallroutineUnionid(String smallroutineUnionid) {
        this.smallroutineUnionid = smallroutineUnionid == null ? null : smallroutineUnionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.phone_type
     *
     * @return the value of t_loyalty_member.phone_type
     *
     * @mbggenerated
     */
    public Integer getPhoneType() {
        return phoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.phone_type
     *
     * @param phoneType the value for t_loyalty_member.phone_type
     *
     * @mbggenerated
     */
    public void setPhoneType(Integer phoneType) {
        this.phoneType = phoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loyalty_member.push_id
     *
     * @return the value of t_loyalty_member.push_id
     *
     * @mbggenerated
     */
    public String getPushId() {
        return pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loyalty_member.push_id
     *
     * @param pushId the value for t_loyalty_member.push_id
     *
     * @mbggenerated
     */
    public void setPushId(String pushId) {
        this.pushId = pushId == null ? null : pushId.trim();
    }
}