server:
  port: 8086
  servlet:
    session:
      timeout: 30M
spring:
  application:
    name: roncoo-pay-app-notify
logging:
  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml