server:
  port: 8088
  servlet:
    session:
      timeout: 30M
spring:
  application:
    name: roncoo-pay-app-reconciliation
logging:
  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml

