version: '2'
services:
  eureka-server:
    image: yzh/eureka_server
    ports:
      - "8000:8000"

  config-server:
    image: yzh/config-server
    links: eureka-server
    ports:
      - "8001:8001"

  base-server:
    image: yzh/base-server
    links :
      - eureka-server
      - config-server
    ports:
    -   - "8002:8002"
