package com.learn.yzh.common.model.Cards;

import java.io.Serializable;
import java.util.Date;

public class CardApplyVO  implements Serializable {

    private static final long serialVersionUID = 3571812780126089678L;

    private String caeateName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.card_code
     *
     * @mbggenerated
     */
    private String cardCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.apply_name
     *
     * @mbggenerated
     */
    private String applyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.apply_num
     *
     * @mbggenerated
     */
    private Integer applyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.expire_type
     *
     * @mbggenerated
     */
    private Integer expireType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.expire_start_time
     *
     * @mbggenerated
     */
    private Date expireStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.expire_end_time
     *
     * @mbggenerated
     */
    private Date expireEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.expire_days
     *
     * @mbggenerated
     */
    private Integer expireDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.apply_comment
     *
     * @mbggenerated
     */
    private String applyComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.company_code
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.export
     *
     * @mbggenerated
     */
    private Integer export;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.export_time
     *
     * @mbggenerated
     */
    private Date exportTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.export_by
     *
     * @mbggenerated
     */
    private String exportBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.export_by_name
     *
     * @mbggenerated
     */
    private String exportByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_apply.update_by
     *
     * @mbggenerated
     */
    private String updateBy;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.id
     *
     * @return the value of t_card_apply.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.id
     *
     * @param id the value for t_card_apply.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.card_code
     *
     * @return the value of t_card_apply.card_code
     *
     * @mbggenerated
     */
    public String getCardCode() {
        return cardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.card_code
     *
     * @param cardCode the value for t_card_apply.card_code
     *
     * @mbggenerated
     */
    public void setCardCode(String cardCode) {
        this.cardCode = cardCode == null ? null : cardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.apply_name
     *
     * @return the value of t_card_apply.apply_name
     *
     * @mbggenerated
     */
    public String getApplyName() {
        return applyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.apply_name
     *
     * @param applyName the value for t_card_apply.apply_name
     *
     * @mbggenerated
     */
    public void setApplyName(String applyName) {
        this.applyName = applyName == null ? null : applyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.apply_num
     *
     * @return the value of t_card_apply.apply_num
     *
     * @mbggenerated
     */
    public Integer getApplyNum() {
        return applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.apply_num
     *
     * @param applyNum the value for t_card_apply.apply_num
     *
     * @mbggenerated
     */
    public void setApplyNum(Integer applyNum) {
        this.applyNum = applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.expire_type
     *
     * @return the value of t_card_apply.expire_type
     *
     * @mbggenerated
     */
    public Integer getExpireType() {
        return expireType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.expire_type
     *
     * @param expireType the value for t_card_apply.expire_type
     *
     * @mbggenerated
     */
    public void setExpireType(Integer expireType) {
        this.expireType = expireType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.expire_start_time
     *
     * @return the value of t_card_apply.expire_start_time
     *
     * @mbggenerated
     */
    public Date getExpireStartTime() {
        return expireStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.expire_start_time
     *
     * @param expireStartTime the value for t_card_apply.expire_start_time
     *
     * @mbggenerated
     */
    public void setExpireStartTime(Date expireStartTime) {
        this.expireStartTime = expireStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.expire_end_time
     *
     * @return the value of t_card_apply.expire_end_time
     *
     * @mbggenerated
     */
    public Date getExpireEndTime() {
        return expireEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.expire_end_time
     *
     * @param expireEndTime the value for t_card_apply.expire_end_time
     *
     * @mbggenerated
     */
    public void setExpireEndTime(Date expireEndTime) {
        this.expireEndTime = expireEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.expire_days
     *
     * @return the value of t_card_apply.expire_days
     *
     * @mbggenerated
     */
    public Integer getExpireDays() {
        return expireDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.expire_days
     *
     * @param expireDays the value for t_card_apply.expire_days
     *
     * @mbggenerated
     */
    public void setExpireDays(Integer expireDays) {
        this.expireDays = expireDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.apply_comment
     *
     * @return the value of t_card_apply.apply_comment
     *
     * @mbggenerated
     */
    public String getApplyComment() {
        return applyComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.apply_comment
     *
     * @param applyComment the value for t_card_apply.apply_comment
     *
     * @mbggenerated
     */
    public void setApplyComment(String applyComment) {
        this.applyComment = applyComment == null ? null : applyComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.company_code
     *
     * @return the value of t_card_apply.company_code
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.company_code
     *
     * @param companyCode the value for t_card_apply.company_code
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.export
     *
     * @return the value of t_card_apply.export
     *
     * @mbggenerated
     */
    public Integer getExport() {
        return export;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.export
     *
     * @param export the value for t_card_apply.export
     *
     * @mbggenerated
     */
    public void setExport(Integer export) {
        this.export = export;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.export_time
     *
     * @return the value of t_card_apply.export_time
     *
     * @mbggenerated
     */
    public Date getExportTime() {
        return exportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.export_time
     *
     * @param exportTime the value for t_card_apply.export_time
     *
     * @mbggenerated
     */
    public void setExportTime(Date exportTime) {
        this.exportTime = exportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.export_by
     *
     * @return the value of t_card_apply.export_by
     *
     * @mbggenerated
     */
    public String getExportBy() {
        return exportBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.export_by
     *
     * @param exportBy the value for t_card_apply.export_by
     *
     * @mbggenerated
     */
    public void setExportBy(String exportBy) {
        this.exportBy = exportBy == null ? null : exportBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.export_by_name
     *
     * @return the value of t_card_apply.export_by_name
     *
     * @mbggenerated
     */
    public String getExportByName() {
        return exportByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.export_by_name
     *
     * @param exportByName the value for t_card_apply.export_by_name
     *
     * @mbggenerated
     */
    public void setExportByName(String exportByName) {
        this.exportByName = exportByName == null ? null : exportByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.status
     *
     * @return the value of t_card_apply.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.status
     *
     * @param status the value for t_card_apply.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.del_flag
     *
     * @return the value of t_card_apply.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.del_flag
     *
     * @param delFlag the value for t_card_apply.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.create_time
     *
     * @return the value of t_card_apply.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.create_time
     *
     * @param createTime the value for t_card_apply.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.create_by
     *
     * @return the value of t_card_apply.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.create_by
     *
     * @param createBy the value for t_card_apply.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.update_time
     *
     * @return the value of t_card_apply.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.update_time
     *
     * @param updateTime the value for t_card_apply.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_apply.update_by
     *
     * @return the value of t_card_apply.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_apply.update_by
     *
     * @param updateBy the value for t_card_apply.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    public String getCaeateName() {
        return caeateName;
    }

    public void setCaeateName(String caeateName) {
        this.caeateName = caeateName;
    }

    @Override
    public String toString() {
        return super.toString();
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }
}
