package com.learn.yzh.common.model.movie;

import java.io.Serializable;
import java.util.Date;

public class MovieSeat implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.cinema_code
     *
     * @mbggenerated
     */
    private String cinemaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.hall_code
     *
     * @mbggenerated
     */
    private String hallCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.seat_no
     *
     * @mbggenerated
     */
    private String seatNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.col_id
     *
     * @mbggenerated
     */
    private String colId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.row_id
     *
     * @mbggenerated
     */
    private String rowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.col_num
     *
     * @mbggenerated
     */
    private Integer colNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.row_num
     *
     * @mbggenerated
     */
    private Integer rowNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.seat_status
     *
     * @mbggenerated
     */
    private String seatStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.loveseats
     *
     * @mbggenerated
     */
    private String loveseats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.seat_type
     *
     * @mbggenerated
     */
    private String seatType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.damage
     *
     * @mbggenerated
     */
    private String damage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_seat.section_id
     *
     * @mbggenerated
     */
    private String sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_movie_seat
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.id
     *
     * @return the value of t_movie_seat.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.id
     *
     * @param id the value for t_movie_seat.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.cinema_code
     *
     * @return the value of t_movie_seat.cinema_code
     *
     * @mbggenerated
     */
    public String getCinemaCode() {
        return cinemaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.cinema_code
     *
     * @param cinemaCode the value for t_movie_seat.cinema_code
     *
     * @mbggenerated
     */
    public void setCinemaCode(String cinemaCode) {
        this.cinemaCode = cinemaCode == null ? null : cinemaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.hall_code
     *
     * @return the value of t_movie_seat.hall_code
     *
     * @mbggenerated
     */
    public String getHallCode() {
        return hallCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.hall_code
     *
     * @param hallCode the value for t_movie_seat.hall_code
     *
     * @mbggenerated
     */
    public void setHallCode(String hallCode) {
        this.hallCode = hallCode == null ? null : hallCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.seat_no
     *
     * @return the value of t_movie_seat.seat_no
     *
     * @mbggenerated
     */
    public String getSeatNo() {
        return seatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.seat_no
     *
     * @param seatNo the value for t_movie_seat.seat_no
     *
     * @mbggenerated
     */
    public void setSeatNo(String seatNo) {
        this.seatNo = seatNo == null ? null : seatNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.col_id
     *
     * @return the value of t_movie_seat.col_id
     *
     * @mbggenerated
     */
    public String getColId() {
        return colId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.col_id
     *
     * @param colId the value for t_movie_seat.col_id
     *
     * @mbggenerated
     */
    public void setColId(String colId) {
        this.colId = colId == null ? null : colId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.row_id
     *
     * @return the value of t_movie_seat.row_id
     *
     * @mbggenerated
     */
    public String getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.row_id
     *
     * @param rowId the value for t_movie_seat.row_id
     *
     * @mbggenerated
     */
    public void setRowId(String rowId) {
        this.rowId = rowId == null ? null : rowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.col_num
     *
     * @return the value of t_movie_seat.col_num
     *
     * @mbggenerated
     */
    public Integer getColNum() {
        return colNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.col_num
     *
     * @param colNum the value for t_movie_seat.col_num
     *
     * @mbggenerated
     */
    public void setColNum(Integer colNum) {
        this.colNum = colNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.row_num
     *
     * @return the value of t_movie_seat.row_num
     *
     * @mbggenerated
     */
    public Integer getRowNum() {
        return rowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.row_num
     *
     * @param rowNum the value for t_movie_seat.row_num
     *
     * @mbggenerated
     */
    public void setRowNum(Integer rowNum) {
        this.rowNum = rowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.seat_status
     *
     * @return the value of t_movie_seat.seat_status
     *
     * @mbggenerated
     */
    public String getSeatStatus() {
        return seatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.seat_status
     *
     * @param seatStatus the value for t_movie_seat.seat_status
     *
     * @mbggenerated
     */
    public void setSeatStatus(String seatStatus) {
        this.seatStatus = seatStatus == null ? null : seatStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.loveseats
     *
     * @return the value of t_movie_seat.loveseats
     *
     * @mbggenerated
     */
    public String getLoveseats() {
        return loveseats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.loveseats
     *
     * @param loveseats the value for t_movie_seat.loveseats
     *
     * @mbggenerated
     */
    public void setLoveseats(String loveseats) {
        this.loveseats = loveseats == null ? null : loveseats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.seat_type
     *
     * @return the value of t_movie_seat.seat_type
     *
     * @mbggenerated
     */
    public String getSeatType() {
        return seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.seat_type
     *
     * @param seatType the value for t_movie_seat.seat_type
     *
     * @mbggenerated
     */
    public void setSeatType(String seatType) {
        this.seatType = seatType == null ? null : seatType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.create_by
     *
     * @return the value of t_movie_seat.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.create_by
     *
     * @param createBy the value for t_movie_seat.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.create_time
     *
     * @return the value of t_movie_seat.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.create_time
     *
     * @param createTime the value for t_movie_seat.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.update_by
     *
     * @return the value of t_movie_seat.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.update_by
     *
     * @param updateBy the value for t_movie_seat.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.update_time
     *
     * @return the value of t_movie_seat.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.update_time
     *
     * @param updateTime the value for t_movie_seat.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.del_flag
     *
     * @return the value of t_movie_seat.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.del_flag
     *
     * @param delFlag the value for t_movie_seat.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.damage
     *
     * @return the value of t_movie_seat.damage
     *
     * @mbggenerated
     */
    public String getDamage() {
        return damage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.damage
     *
     * @param damage the value for t_movie_seat.damage
     *
     * @mbggenerated
     */
    public void setDamage(String damage) {
        this.damage = damage == null ? null : damage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_seat.section_id
     *
     * @return the value of t_movie_seat.section_id
     *
     * @mbggenerated
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_seat.section_id
     *
     * @param sectionId the value for t_movie_seat.section_id
     *
     * @mbggenerated
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId == null ? null : sectionId.trim();
    }
}