package com.learn.yzh.common.model.movie;

import java.io.Serializable;
import java.util.Date;

public class MovieHall implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.cinema_code
     *
     * @mbggenerated
     */
    private String cinemaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.hall_code
     *
     * @mbggenerated
     */
    private String hallCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.hall_name
     *
     * @mbggenerated
     */
    private String hallName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.hall_capacity
     *
     * @mbggenerated
     */
    private String hallCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.hall_max_row
     *
     * @mbggenerated
     */
    private Integer hallMaxRow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.hall_max_col
     *
     * @mbggenerated
     */
    private Integer hallMaxCol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.hall_sight
     *
     * @mbggenerated
     */
    private String hallSight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.is_special
     *
     * @mbggenerated
     */
    private String isSpecial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.server_brand
     *
     * @mbggenerated
     */
    private String serverBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.server_sn
     *
     * @mbggenerated
     */
    private String serverSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.projector_brand
     *
     * @mbggenerated
     */
    private String projectorBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.projector_sn
     *
     * @mbggenerated
     */
    private String projectorSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_movie_hall.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_movie_hall
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.id
     *
     * @return the value of t_movie_hall.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.id
     *
     * @param id the value for t_movie_hall.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.cinema_code
     *
     * @return the value of t_movie_hall.cinema_code
     *
     * @mbggenerated
     */
    public String getCinemaCode() {
        return cinemaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.cinema_code
     *
     * @param cinemaCode the value for t_movie_hall.cinema_code
     *
     * @mbggenerated
     */
    public void setCinemaCode(String cinemaCode) {
        this.cinemaCode = cinemaCode == null ? null : cinemaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.hall_code
     *
     * @return the value of t_movie_hall.hall_code
     *
     * @mbggenerated
     */
    public String getHallCode() {
        return hallCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.hall_code
     *
     * @param hallCode the value for t_movie_hall.hall_code
     *
     * @mbggenerated
     */
    public void setHallCode(String hallCode) {
        this.hallCode = hallCode == null ? null : hallCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.hall_name
     *
     * @return the value of t_movie_hall.hall_name
     *
     * @mbggenerated
     */
    public String getHallName() {
        return hallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.hall_name
     *
     * @param hallName the value for t_movie_hall.hall_name
     *
     * @mbggenerated
     */
    public void setHallName(String hallName) {
        this.hallName = hallName == null ? null : hallName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.hall_capacity
     *
     * @return the value of t_movie_hall.hall_capacity
     *
     * @mbggenerated
     */
    public String getHallCapacity() {
        return hallCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.hall_capacity
     *
     * @param hallCapacity the value for t_movie_hall.hall_capacity
     *
     * @mbggenerated
     */
    public void setHallCapacity(String hallCapacity) {
        this.hallCapacity = hallCapacity == null ? null : hallCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.hall_max_row
     *
     * @return the value of t_movie_hall.hall_max_row
     *
     * @mbggenerated
     */
    public Integer getHallMaxRow() {
        return hallMaxRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.hall_max_row
     *
     * @param hallMaxRow the value for t_movie_hall.hall_max_row
     *
     * @mbggenerated
     */
    public void setHallMaxRow(Integer hallMaxRow) {
        this.hallMaxRow = hallMaxRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.hall_max_col
     *
     * @return the value of t_movie_hall.hall_max_col
     *
     * @mbggenerated
     */
    public Integer getHallMaxCol() {
        return hallMaxCol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.hall_max_col
     *
     * @param hallMaxCol the value for t_movie_hall.hall_max_col
     *
     * @mbggenerated
     */
    public void setHallMaxCol(Integer hallMaxCol) {
        this.hallMaxCol = hallMaxCol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.hall_sight
     *
     * @return the value of t_movie_hall.hall_sight
     *
     * @mbggenerated
     */
    public String getHallSight() {
        return hallSight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.hall_sight
     *
     * @param hallSight the value for t_movie_hall.hall_sight
     *
     * @mbggenerated
     */
    public void setHallSight(String hallSight) {
        this.hallSight = hallSight == null ? null : hallSight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.is_special
     *
     * @return the value of t_movie_hall.is_special
     *
     * @mbggenerated
     */
    public String getIsSpecial() {
        return isSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.is_special
     *
     * @param isSpecial the value for t_movie_hall.is_special
     *
     * @mbggenerated
     */
    public void setIsSpecial(String isSpecial) {
        this.isSpecial = isSpecial == null ? null : isSpecial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.server_brand
     *
     * @return the value of t_movie_hall.server_brand
     *
     * @mbggenerated
     */
    public String getServerBrand() {
        return serverBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.server_brand
     *
     * @param serverBrand the value for t_movie_hall.server_brand
     *
     * @mbggenerated
     */
    public void setServerBrand(String serverBrand) {
        this.serverBrand = serverBrand == null ? null : serverBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.server_sn
     *
     * @return the value of t_movie_hall.server_sn
     *
     * @mbggenerated
     */
    public String getServerSn() {
        return serverSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.server_sn
     *
     * @param serverSn the value for t_movie_hall.server_sn
     *
     * @mbggenerated
     */
    public void setServerSn(String serverSn) {
        this.serverSn = serverSn == null ? null : serverSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.projector_brand
     *
     * @return the value of t_movie_hall.projector_brand
     *
     * @mbggenerated
     */
    public String getProjectorBrand() {
        return projectorBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.projector_brand
     *
     * @param projectorBrand the value for t_movie_hall.projector_brand
     *
     * @mbggenerated
     */
    public void setProjectorBrand(String projectorBrand) {
        this.projectorBrand = projectorBrand == null ? null : projectorBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.projector_sn
     *
     * @return the value of t_movie_hall.projector_sn
     *
     * @mbggenerated
     */
    public String getProjectorSn() {
        return projectorSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.projector_sn
     *
     * @param projectorSn the value for t_movie_hall.projector_sn
     *
     * @mbggenerated
     */
    public void setProjectorSn(String projectorSn) {
        this.projectorSn = projectorSn == null ? null : projectorSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.create_by
     *
     * @return the value of t_movie_hall.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.create_by
     *
     * @param createBy the value for t_movie_hall.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.create_time
     *
     * @return the value of t_movie_hall.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.create_time
     *
     * @param createTime the value for t_movie_hall.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.update_by
     *
     * @return the value of t_movie_hall.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.update_by
     *
     * @param updateBy the value for t_movie_hall.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.update_time
     *
     * @return the value of t_movie_hall.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.update_time
     *
     * @param updateTime the value for t_movie_hall.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_movie_hall.del_flag
     *
     * @return the value of t_movie_hall.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_movie_hall.del_flag
     *
     * @param delFlag the value for t_movie_hall.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}